kind: pipeline
name: default
type: docker

steps:
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: md5lukas/drone-artifact-shelf
      auto_tag: true